export default {
  home: {
    eventsAroundYourCity: 'Events around your city',
    location: 'Location',
    add: 'Add',
    search: 'Search',
    viewAll: 'View All',
    todayLessons: 'Today Lessons',
    mostPopularLessons: 'Most Popular Lessons',
    recentlyAddedLessons: 'Recently Added Lessons',
  },
  modal: {
    close: 'Close',
    addNew: 'Add New',
    filter: 'Filter',
    synagogue: 'Synagogue',
    lesson: 'Lesson',
    addNewLesson: 'Add New Lesson',
    enterSubject: 'Enter Subject',
    enterSubjectHere: 'Enter subject here...',
    speaker: 'Speaker',
    addNewSpeaker: 'Add New Speaker',
    selectSpeaker: 'Select Speaker',
    location: 'Location',
    enterLocation: 'Enter location...',
    timeAndDate: 'Time and Date',
    setDays: 'Set Days',
    weeklyRecurrence: 'Weekly recurrence',
    description: 'Description',
    enterDescription: 'Enter description...',
    contactName: 'Contact Name',
    enterNameHere: 'Enter name here...',
    contactNumber: 'Contact Number',
    enterNumberHere: 'Enter number here...',
    audience: 'Audience',
    selectAudience: 'Select Audience',
    publishLessons: 'Publish Lessons',

    addNewSynagogue: 'Add New Synagogue',
    synagogueName: 'Synagogue Name *',
    enterSynagogueNameHere: 'Enter synagogue name here...',
    nosach: 'Nosach',
    selectNosach: 'Select nosach...',
    addMinTimes: 'Add min times',
    shachrit: 'Shachrit',
    maariv: 'Maariv',
    selectDateTime: 'Select date / time',
    remove: 'Remove',
    daily: 'Daily',
    shtiblach: 'Shtiblach',
    amenities: 'Amenities',
    selectAmenities: 'Select amenities...',
    notes: 'Notes',
    enterNotes: 'Enter notes...',
    ownerContactNumber: 'Owner Contact Number',
    upload: 'Upload',
    synagoguePicture: 'Synagogue Picture',

    bothLessonsAndSynagogue: 'Both Lessons & Synagogue',
  },
  detail: {
    comments: 'Comments',
    like: 'Like',
    unlike: 'Unlike',
    liked: 'liked',
    typeCommentHere: 'Type comment here...',
  },
  searchHistory: {
    searchHistory: 'Search History',
    date: 'Date',
    newSearch: 'New Search',
  },
  searchResult: {
    mapView: 'Map View',
    newSearch: 'New Search',
    navigate: 'Navigate',
    resultsFound: 'results found',
    radius: 'radius',
  },
  filter: {
    searchBySpeakerName: 'Search by speaker name',
    searchByLocation: 'Search by location',
    sortResults: 'Sort results',
    nearBy: 'Nearby',
    time: 'Time',
    clear: 'Clear',
    timeRange: 'Time Range',
    radius: 'Radius',
    searchingTypes: 'Searching Types',
    reset: 'Reset',
  },
  synagogue: {
    lastUpdated: 'Last updated',
    ago: 'ago',
    days: 'days',
    donate: 'donate',
    minamynTimes: 'Minamym times',
    lessonsTimes: 'Lessons times',
  },
  memorial: {
    splash_screen: 'In memory of David Jefry',
    all_over_the_app: 'For the health of Sarah Cohen',
  },
  nosach: {
    value_0: 'Ashkenaz',
    value_1: 'Sefard',
    value_2: 'Edot Hamizrah',
    value_3: 'Ar"i',
    value_4: 'Chabad',
    value_5: 'Temani',
  },
  amenities: {
    value_0: 'Sefer Torah',
    value_1: 'Disabled Access',
    value_2: 'Parking',
    value_3: 'Women Section',
  },
  weekDay: {
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
  },
  audience: {
    men: 'Men',
    women: 'Women',
    men_and_women: 'Men and Women',
  },
  menu: {
    myProfile: 'My Profile',
    settings: 'Settings',
    favorite: 'Favorite',
    switchLanguage: 'החלף לעברית',
    logout: 'Logout',
  },

  profile: {
    enterNewNameHere: 'Enter new name here',
    enterNewEmailHere: 'Enter new email address here',
  },

  changeLocation: 'Change Location',
  setYourHomeCity: 'Set your home city',
  unDefined: 'UnDefined',
  notHere: 'Not Here?',
  clickHereToCreateNewSyna: 'Click here to create a new Synagogue',
  pleaseTypeTheSynagogueName: 'Please type the Synagogue Name',
};
