export default {
  home: {
    eventsAroundYourCity: 'אירועים בקרבת מקום',
    location: 'מיקום',
    add: 'הוספה',
    search: 'חיפוש',
    viewAll: 'הצג הכל',
    todayLessons: 'שיעורי היום',
    mostPopularLessons: 'השיעורים הפופולאריים ביותר',
    recentlyAddedLessons: 'התווספו לאחרונה',
  },
  modal: {
    close: 'סגור',
    addNew: 'הוספה',
    filter: 'סנן',
    synagogue: 'בית כנסת',
    lesson: 'שיעור תורה',
    addNewLesson: 'הוסף שיעור חדש',
    enterSubject: 'הזן נושא',
    enterSubjectHere: 'הזן נושא',
    speaker: 'מעביר השיעור',
    addNewSpeaker: 'הוסף מעביר שיעור',
    selectSpeaker: 'בחר מעביר שיעור',
    location: 'מיקום',
    enterLocation: 'הזן מיקום...',
    timeAndDate: 'זמן ותאריך',
    setDays: 'קביעת ימים',
    weeklyRecurrence: 'שבועי',
    description: 'תיאור',
    enterDescription: 'הזן תיאור...',
    contactName: 'שם איש קשר',
    enterNameHere: 'Enter name here...',
    contactNumber: 'מספר איש קשר',
    enterNumberHere: 'הזן מספר כאן...',
    audience: 'גבר / נשים',
    selectAudience: 'סתם גבר, סתם נשים או גבר ונשים',
    publishLessons: 'פרסם שיעור',

    addNewSynagogue: 'הוספת בית כנסת חדש',
    synagogueName: 'שם בית הכנסת *',
    enterSynagogueNameHere: 'הזן כאן את שם בית הכנסת...',
    nosach: 'נוסח',
    selectNosach: 'בחר נוסח...',
    addMinTimes: 'הוסף זמני תפילות',
    shachrit: 'שחרית',
    selectDateTime: 'בחר תאריך / זמן',
    remove: 'הסר',
    daily: 'יומי',
    shtiblach: 'האם זה שטיבלך ',
    amenities: 'מידע ',
    selectAmenities: 'הוסף מידע נוסף...',
    notes: 'הערות',
    enterNotes: 'הוסף הערה...',
    ownerContactNumber: 'טלפון ליצירת קשר',
    upload: 'העלאה',
    synagoguePicture: 'תמונות בית הכנסת',

    bothLessonsAndSynagogue: 'שיעור תורה & בית כנסת',
  },
  detail: {
    comments: 'תגובות',
    like: 'אוהב',
    liked: 'אהבו',
    typeCommentHere: 'הזן תגובה כאן...',
  },
  searchHistory: {
    searchHistory: 'היסטוריית חיפוש',
    date: 'תאריך',
    newSearch: 'חיפוש חדש',
  },
  searchResult: {
    mapView: 'תצוגת מפה',
    newSearch: 'חיפוש חדש',
    navigate: 'נווט',
    resultsFound: 'נמצאו תוצאות',
    radius: 'סביב מיקום',
  },
  filter: {
    searchBySpeakerName: 'חיפוש לפי מעביר שיעור',
    searchByLocation: 'חיפוש לפי מיקום',
    sortResults: 'מיון תוצאות',
    nearBy: 'קרוב אליי',
    time: 'מתרחש בקרוב',
    clear: 'נקה',
    timeRange: 'טווח זמן',
    searchingTypes: 'סוגי החיפוש',
    reset: 'אפס',
  },
  synagogue: {
    lastUpdated: 'עודכן לאחרונה',
    ago: 'לפני',
    days: 'יום',
    donate: 'לתרום',
    minamynTimes: 'זמני תפילה',
    lessonsTimes: 'שיעורים פעמים',
  },
  memorial: {
    splash_screen: 'לעילוי נשמה פלוני בן אלמוני',
    all_over_the_app: 'לרפואת אלף בית גימל',
  },
  nosach: {
    value_0: 'אשכנזי',
    value_1: 'ספרד',
    value_2: 'עדות המזרח',
    value_3: 'אר"י',
    value_4: 'חב"ד',
    value_5: 'תימני',
  },
  amenities: {
    value_0: 'ספר תורה',
    value_1: 'נגישות',
    value_2: 'חניה',
    value_3: 'עזרת נשים',
  },
  weekDay: {
    mon: 'שני',
    tue: 'שלישי',
    wed: 'רביעי',
    thu: 'חמישי',
    fri: 'שישי',
    sat: 'שבת',
    sun: 'ראשון',
  },
  audience: {
    men: 'גברים',
    women: 'נשים',
    men_and_women: 'גברים ונשים',
  },
};
