export default {
  // non-editable values
  MODAL_FLAG_ADD_LESSON: 'MODAL_FLAG_ADD_LESSON',
  MODAL_FLAG_ADD_SYN: 'MODAL_FLAG_ADD_SYN',
  LS_LANGUAGE: 'LANGUAGE',
  ENGLISH: 'ENGLISH',
  HEBREW: 'HEBREW',
  INTRO_CHECKED: 'INTRO_CHECKED',
  LOGGED_IN: 'LOGGED_IN',
  FLAG_TRUE: 'true',
  FLAG_FALSE: 'false',
  TOKEN: 'TOKEN',
  TEST_TOKEN:
    'eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVkNzI4YWY1NTI5YjczMDk2MDUzNzI4NyIsImVtYWlsIjoia2FyaW1vZGVzaWduQGdtYWlsLmNvbSJ9.XOKnG-eYFmRM9OK_-ikLKWljIdfT9mLzlqYnEWhOKtw',
  LOGIN_TYPE: 'LOGIN_TYPE',
  LOGIN_TYPE_FACEBOOK: 'LOGIN_TYPE_FACEBOOK',
  LOGIN_TYPE_GOOGLE: 'LOGIN_TYPE_GOOGLE',
  LOGIN_TYPE_EMAIL: 'LOGIN_TYPE_EMAIL',

  // editable values
  localToken: '',
  loginType: '',
};
