export default {
  MODAL_FLAG_ADD_LESSON: 'MODAL_FLAG_ADD_LESSON',
  MODAL_FLAG_ADD_SYN: 'MODAL_FLAG_ADD_SYN',
  LS_LANGUAGE: 'LANGUAGE',
  ENGLISH: 'ENGLISH',
  HEBREW: 'HEBREW',
  INTRO_CHECKED: 'INTRO_CHECKED',
  LOGGED_IN: 'LOGGED_IN',
  FLAG_TRUE: 'true',
  FLAG_FALSE: 'false',
};
